# fly.toml app configuration file generated for htmx-todo
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'htmx-todo'
primary_region = 'yul'

[build]

[http_service]
auto_start_machines = true
auto_stop_machines = true
force_https = true
internal_port = 3000
min_machines_running = 0
processes = ['app']

[[vm]]
size = 'shared-cpu-1x'
